vich_uploader:
    db_driver: orm

    mappings:
        character_picture:
            uri_prefix: /images/characters
            upload_destination: '%kernel.project_dir%/public/images/characters'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            
        character_feature_picture:
            uri_prefix: /images/characters/features
            upload_destination: '%kernel.project_dir%/public/images/characters/features'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            
        character_profession_picture:
            uri_prefix: /images/characters/badges/professions
            upload_destination: '%kernel.project_dir%/public/images/characters/badges/professions'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        character_profession_speciality_picture:
            uri_prefix: /images/characters/badges/professions/specialties
            upload_destination: '%kernel.project_dir%/public/images/characters/badges/professions/specialties'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        character_rank_picture:
            uri_prefix: /images/characters/badges/ranks
            upload_destination: '%kernel.project_dir%/public/images/characters/badges/ranks'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        character_skill_picture:
            uri_prefix: /images/characters/skills
            upload_destination: '%kernel.project_dir%/public/images/characters/skills'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        illustration_picture:
            uri_prefix: /images/illustrations
            upload_destination: '%kernel.project_dir%/public/images/illustrations'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        character_medal_picture:
            uri_prefix: /images/characters/medals
            upload_destination: '%kernel.project_dir%/public/images/characters/medals'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        character_medal_ribbon_picture:
            uri_prefix: /images/characters/medals/ribbons
            upload_destination: '%kernel.project_dir%/public/images/characters/medals/ribbons'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        user_picture:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
