vich_uploader:
    db_driver: orm

    mappings:
        users_pictures:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        medals_pictures:
            uri_prefix: /images/medals
            upload_destination: '%kernel.project_dir%/public/images/medals'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        medals_reductions:
            uri_prefix: /images/medals/reductions
            upload_destination: '%kernel.project_dir%/public/images/medals/reductions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        illustrations_pictures:
            uri_prefix: /images/illustrations
            upload_destination: '%kernel.project_dir%/public/images/illustrations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
